// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package del

import (
	"sync"
)

// Ensure, that AliasDeleterMock does implement AliasDeleter.
// If this is not the case, regenerate this file with moq.
var _ AliasDeleter = &AliasDeleterMock{}

// AliasDeleterMock is a mock implementation of AliasDeleter.
//
//	func TestSomethingThatUsesAliasDeleter(t *testing.T) {
//
//		// make and configure a mocked AliasDeleter
//		mockedAliasDeleter := &AliasDeleterMock{
//			DeleteAliasFunc: func(alias string) error {
//				panic("mock out the DeleteAlias method")
//			},
//		}
//
//		// use mockedAliasDeleter in code that requires AliasDeleter
//		// and then make assertions.
//
//	}
type AliasDeleterMock struct {
	// DeleteAliasFunc mocks the DeleteAlias method.
	DeleteAliasFunc func(alias string) error

	// calls tracks calls to the methods.
	calls struct {
		// DeleteAlias holds details about calls to the DeleteAlias method.
		DeleteAlias []struct {
			// Alias is the alias argument value.
			Alias string
		}
	}
	lockDeleteAlias sync.RWMutex
}

// DeleteAlias calls DeleteAliasFunc.
func (mock *AliasDeleterMock) DeleteAlias(alias string) error {
	if mock.DeleteAliasFunc == nil {
		panic("AliasDeleterMock.DeleteAliasFunc: method is nil but AliasDeleter.DeleteAlias was just called")
	}
	callInfo := struct {
		Alias string
	}{
		Alias: alias,
	}
	mock.lockDeleteAlias.Lock()
	mock.calls.DeleteAlias = append(mock.calls.DeleteAlias, callInfo)
	mock.lockDeleteAlias.Unlock()
	return mock.DeleteAliasFunc(alias)
}

// DeleteAliasCalls gets all the calls that were made to DeleteAlias.
// Check the length with:
//
//	len(mockedAliasDeleter.DeleteAliasCalls())
func (mock *AliasDeleterMock) DeleteAliasCalls() []struct {
	Alias string
} {
	var calls []struct {
		Alias string
	}
	mock.lockDeleteAlias.RLock()
	calls = mock.calls.DeleteAlias
	mock.lockDeleteAlias.RUnlock()
	return calls
}
