// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package redirect

import (
	"sync"
)

// Ensure, that URLGetterMock does implement URLGetter.
// If this is not the case, regenerate this file with moq.
var _ URLGetter = &URLGetterMock{}

// URLGetterMock is a mock implementation of URLGetter.
//
//	func TestSomethingThatUsesURLGetter(t *testing.T) {
//
//		// make and configure a mocked URLGetter
//		mockedURLGetter := &URLGetterMock{
//			GetURLFunc: func(alias string) (string, error) {
//				panic("mock out the GetURL method")
//			},
//		}
//
//		// use mockedURLGetter in code that requires URLGetter
//		// and then make assertions.
//
//	}
type URLGetterMock struct {
	// GetURLFunc mocks the GetURL method.
	GetURLFunc func(alias string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetURL holds details about calls to the GetURL method.
		GetURL []struct {
			// Alias is the alias argument value.
			Alias string
		}
	}
	lockGetURL sync.RWMutex
}

// GetURL calls GetURLFunc.
func (mock *URLGetterMock) GetURL(alias string) (string, error) {
	if mock.GetURLFunc == nil {
		panic("URLGetterMock.GetURLFunc: method is nil but URLGetter.GetURL was just called")
	}
	callInfo := struct {
		Alias string
	}{
		Alias: alias,
	}
	mock.lockGetURL.Lock()
	mock.calls.GetURL = append(mock.calls.GetURL, callInfo)
	mock.lockGetURL.Unlock()
	return mock.GetURLFunc(alias)
}

// GetURLCalls gets all the calls that were made to GetURL.
// Check the length with:
//
//	len(mockedURLGetter.GetURLCalls())
func (mock *URLGetterMock) GetURLCalls() []struct {
	Alias string
} {
	var calls []struct {
		Alias string
	}
	mock.lockGetURL.RLock()
	calls = mock.calls.GetURL
	mock.lockGetURL.RUnlock()
	return calls
}
